// Demo lecture data
const lecturesData = [
  {
    id: 1,
    title: "Introduction to Machine Learning",
    module: "AI Fundamentals",
    instructor: "Dr. Sarah Chen",
    duration: "45:32",
    thumbnail: "/machine-learning-course.png",
    description:
      "Learn the fundamentals of machine learning including supervised and unsupervised learning techniques.",
    date: "Nov 15, 2024",
    section: "subscriptions",
  },
  {
    id: 2,
    title: "Neural Networks Deep Dive",
    module: "AI Fundamentals",
    instructor: "Prof. James Wilson",
    duration: "58:15",
    thumbnail: "/neural-networks-visualization.jpg",
    description: "Comprehensive exploration of neural networks, architectures, and training methods.",
    date: "Nov 12, 2024",
    section: "subscriptions",
  },
  {
    id: 3,
    title: "Data Science Best Practices",
    module: "Data Science",
    instructor: "Dr. Maya Patel",
    duration: "52:44",
    thumbnail: "/data-science-dashboard.jpg",
    description: "Industry best practices for data science projects and workflows.",
    date: "Nov 20, 2024",
    section: "subscriptions",
  },
  {
    id: 4,
    title: "Python for Data Analysis",
    module: "Programming",
    instructor: "Alex Rodriguez",
    duration: "63:20",
    thumbnail: "/python-code.png",
    description: "Master Python for data analysis with pandas, numpy, and matplotlib.",
    date: "Nov 18, 2024",
    section: "shared",
  },
  {
    id: 5,
    title: "Web Development Essentials",
    module: "Web Development",
    instructor: "Emma Thompson",
    duration: "47:55",
    thumbnail: "/web-development-interface.jpg",
    description: "Essential concepts and tools for modern web development.",
    date: "Nov 22, 2024",
    section: "shared",
  },
  {
    id: 6,
    title: "Database Design Fundamentals",
    module: "Backend",
    instructor: "Dr. Michael Lee",
    duration: "55:30",
    thumbnail: "/database-schema.png",
    description: "Learn to design efficient and scalable database systems.",
    date: "Nov 24, 2024",
    section: "shared",
  },
  {
    id: 7,
    title: "Cloud Computing with AWS",
    module: "DevOps",
    instructor: "Chris Anderson",
    duration: "61:12",
    thumbnail: "/cloud-computing-infrastructure.jpg",
    description: "Get started with Amazon Web Services and cloud architecture.",
    date: "Nov 25, 2024",
    section: "whats-new",
  },
  {
    id: 8,
    title: "API Design Patterns",
    module: "Backend",
    instructor: "Dr. Lisa Kumar",
    duration: "49:44",
    thumbnail: "/api-rest-architecture.jpg",
    description: "Best practices for designing scalable and maintainable APIs.",
    date: "Nov 26, 2024",
    section: "whats-new",
  },
  {
    id: 9,
    title: "Frontend Performance Optimization",
    module: "Frontend",
    instructor: "Tom Bradley",
    duration: "44:18",
    thumbnail: "/web-performance-metrics.jpg",
    description: "Techniques for optimizing frontend performance and user experience.",
    date: "Nov 27, 2024",
    section: "whats-new",
  },
]

// Sample reel data for side panels
const reelsData = [
  { id: 1, video: "/assets/reel1.mp4" },
  { id: 2, video: "/assets/reel2.mp4" },
  { id: 3, video: "/assets/reel3.mp4" },
]
